FROM anlabkaist/texlive:base
LABEL maintainer="wsyoon@an.kaist.ac.kr"

RUN apt-get update -qq &&\
    DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
      python-pygments \
    && \
    # Clean up
    apt-get autoclean && \
    apt-get autoremove && \
    rm -rf /var/lib/apt/lists/* \
           /tmp/* \
           /var/tmp/* 